### ISSUE TITLE
Os templates estão muito fixos na eesc. Podemos fazer um hangout com ideias tornar essa lib mais abstrata

### ISSUE THREAD

**Issue by thiagogomesverissimo** [uspdev/pdfgen#12]
Em particular, estamos pensando em um sistema interno para para circulação de ofícios e memorando, pensei em usar esse lib para geração dos pdfs.

**Comment by masakik** [comment]
@thiagogomesverissimo alguma continuidade aqui?

**Comment by thiagogomesverissimo** [comment]
Nada. Estou usando o dompdf mesmo e tem sido muito fácil...
